### ISSUE TITLE
roadmap?

### ISSUE THREAD

**Issue by hyusetiawan** [erikvorhes/Utility-Belt-JS#1]
What is the roadmap for this library? Would love to get future updates for more cross browser support

thx

**Comment by erikvorhes** [comment]
No roadmap, really. I might tweak some things or make this better compatible with modern ECMAScript, but unless there are specific issues to address, I don't plan to make any updates at this time.

**Comment by erikvorhes** [comment]
I updated the thing to use an ES2015 class. I’ll consider adding flow typing & maybe convert it into a full-on module with Babel support or whatever, but for now this remains more of an intellectual exercise than something deliberately planned for use in production.
